### ISSUE TITLE
你好，麻烦补充一下这篇论文：Xiao, L., Wang, J., Qiu, X., Rong, Z., & Zou, X. (2019). Dynamic-SLAM: Semantic monocular visual localization and mapping based on deep learning in dynamic environment. Robotics and Autonomous Systems, 117, 1-16. 目前引用量已经200+了

### ISSUE THREAD

**Issue by linhuixiao** [zhuhu00/Awesome_Dynamic_SLAM#1]
你好，方便的话请补充一下这篇论文：Xiao, L., Wang, J., Qiu, X., Rong, Z., & Zou, X. (2019). Dynamic-SLAM: Semantic monocular visual localization and mapping based on deep learning in dynamic environment. Robotics and Autonomous Systems, 117, 1-16. 目前引用量已经200+了
谢谢

**Comment by zhuhu00** [comment]
Done. Thanks a lot~
